---
title             : "Differences in Stress Response by Ethnicity"
shorttitle        : "Mexican Americans vs. White Americans"

author: 
  - name          : "Ruby Cuellar"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Department of Psychology, 1227 University of Oregon, Eugene, OR 97403"
    email         : "rcuellar@uoregon.edu"
  - name          : "Ellen Huang"
    affiliation   : "1"
  - name          : "Angela Lee"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "University of Oregon"

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "sleep, stress, ethnicity"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library(papaja)
library(rio)
library(here)
library(tidyverse)
library(janitor)
library(knitr)
library(kableExtra)
options(scipen=999)

sleep_stress <- import(here("Data","Sleep_Stress_Manuscript_10.10.19.sav")) %>%
  janitor::clean_names() %>%
  select(1:5, 38:44, 47:49) %>%
  as_tibble()
```

```{r data cleaning, include = FALSE}
#tidy bpm variable
tidy <- sleep_stress %>% 
  pivot_longer(
  cols = c("bpm_baseline_mean", "bpm_tsst_mean", "bpm_recovery_mean","hrv_baseline_mean_w", "hrv_tsst_mean_w", "hrv_recovery_mean_w"),
  names_to = c("measure", "timepoint"),
  values_to = "value",
  names_sep = "_", 
  values_drop_na = TRUE
)

#change timepoint and ethnicity to factor 
tidy$timepoint<- factor(tidy$timepoint,levels = c("baseline", "tsst", "recovery"))
tidy$ethnicity <- factor(tidy$ethnicity)

```

# Introduction

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
```{r data analysis, include = FALSE}

meanscore<- tidy %>% 
  group_by(timepoint,measure) %>%
  summarize(meanscores=mean(value))

```

```{r visualization}
#hrv bar graph
tidy %>%
  filter(ethnicity %in% c(0,1), measure=="hrv") %>% 
  ggplot(aes(timepoint, value, fill = ethnicity)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(x="Timepoint", y="Mean HRV", fill="Ethnicity", title= "Mean Heart Rate Variability Across 3 Timepoints") +
  theme_minimal()+
  scale_fill_viridis_d(name = "Ethnicity", labels = c("Mexican", "White"))

#bpm bar graph
tidy %>%
  filter(ethnicity %in% c(0,1), measure=="bpm") %>% 
  ggplot(aes(timepoint, value, fill = ethnicity)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  labs(x="Timepoint", y="Mean BPM", title= "Mean Beats per Minute Across 3 Timepoints")+
  scale_fill_viridis_d(name = "Ethnicity", labels = c("Mexican", "White")) 

wide <-
  pivot_wider(
    tidy,
    names_from = c("measure","timepoint"),
    values_from = value,
    names_sep = "_",
    values_fill = list(value = 0) 
  )


```

```{r summary tables}

means_table <- summarize(wide,
            mean_hrv_baseline = mean(hrv_baseline),
            mean_hrv_tsst = mean(hrv_tsst),
            mean_hrv_recovert = mean(hrv_recovery),
            mean_bpm_baseline = mean(bpm_baseline),
            mean_bpm_tsst = mean(bpm_tsst),
            mean_bpm_recovery = mean(bpm_recovery))

kable(means_table)

```


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
