---
title: "Final Project- Script Draft"
author: "Ruby Cuellar, Angela Lee, Ellen Huang"
date: "11/16/2019"
output: 
  html_document:
    highlight: tango
---

```{r}
library(rio)
library(here)
library(tidyverse)
library(janitor)
library(knitr)
library(kableExtra)
options(scipen=999)

sleep_stress <- import(here("Data","Sleep_Stress_Manuscript_10.10.19.sav")) %>%
  janitor::clean_names() %>%
  select(1:5, 38:44, 47:49) %>%
  as_tibble()
```
```{r recreated hrv bar graph with simpler code}
# Your code is fantastic so didn't want to mess up. Created new code chunk to display everything in one place with shorter code to get 'hrv plot'. Same can be done with 'bpm plot'.  
# added charaterize and drop_na to get cleaner data from the  beginning. Saves several steps of coding later.

#strengths: 1. pivot_longer used nicely, 2. plot : tried several features 3. simplified complicated dataset for visualization nicely
# learning: playing with it taught me to use 'characterize' and "drop_na" at the beginning. I learnt 'dodge' in bar_plot. I also learnt using $ to specify coloumn in datafrmae.
# Areas of improvement: I personally prefer less lines of code as it keeps simple and more understandable for peers. So i tried displaying that in plot.
                        

sleep_stress <- import(here("data","Sleep_Stress_Manuscript_10.10.19.sav")) %>%
  janitor::clean_names() %>%
  as_tibble() %>%
  characterize() %>%   
  drop_na()

sleep_stress1 <- sleep_stress %>%
  select(1:5, 38:44, 47:49) %>%
  as_tibble()

tidy <- sleep_stress1 %>% 
  pivot_longer(
  cols = c("bpm_baseline_mean", "bpm_tsst_mean", "bpm_recovery_mean","hrv_baseline_mean_w", "hrv_tsst_mean_w", "hrv_recovery_mean_w"),
  names_to = c("measure", "timepoint"),
  values_to = "value",
  names_sep = "_")

hrv <- tidy %>%
  select(5, 10 : 12) %>%
  filter(measure == "hrv") %>%
  group_by(timepoint, measure, ethnicity) %>%
  summarize(meanhrv = mean(value))

ggplot(hrv, aes(timepoint, meanhrv, fill = ethnicity)) + 
  geom_bar(stat = "identity", width = 0.5, position = "dodge") + 
  labs(x = "Timepoint", y = "Mean HRV", title = "Mean Heartrate Variability Across 3 Timepoints")


```

```{r data cleaning}
#tidy bpm variable
tidy <- sleep_stress %>% 
  pivot_longer(
  cols = c("bpm_baseline_mean", "bpm_tsst_mean", "bpm_recovery_mean","hrv_baseline_mean_w", "hrv_tsst_mean_w", "hrv_recovery_mean_w"),
  names_to = c("measure", "timepoint"),
  values_to = "value",
  names_sep = "_", 
  values_drop_na = TRUE
)

#change timepoint and ethnicity to factor 
tidy$timepoint<- factor(tidy$timepoint,levels = c("baseline", "tsst", "recovery"))
tidy$ethnicity <- factor(tidy$ethnicity)

meanscore<- tidy %>% 
  group_by(timepoint,measure) %>%
  summarize(meanscores=mean(value))

#hrv bar graph
tidy %>%
  filter(ethnicity %in% c(0,1), measure=="hrv") %>% 
  ggplot(aes(timepoint, value, fill = ethnicity)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(x="Timepoint", y="Mean HRV", fill="Ethnicity", title= "Mean Heart Rate Variability Across 3 Timepoints") +
  theme_minimal()+
  scale_fill_viridis_d(name = "Ethnicity", labels = c("Mexican", "White"))

#bpm bar graph
tidy %>%
  filter(ethnicity %in% c(0,1), measure=="bpm") %>% 
  ggplot(aes(timepoint, value, fill = ethnicity)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal()+
  labs(x="Timepoint", y="Mean BPM", title= "Mean Beats per Minute Across 3 Timepoints")+
  scale_fill_viridis_d(name = "Ethnicity", labels = c("Mexican", "White")) 

wide <-
  pivot_wider(
    tidy,
    names_from = c("measure","timepoint"),
    values_from = value,
    names_sep = "_",
    values_fill = list(value = 0) 
  )

means_table <- summarize(wide,
            mean_hrv_baseline = mean(hrv_baseline),
            mean_hrv_tsst = mean(hrv_tsst),
            mean_hrv_recovert = mean(hrv_recovery),
            mean_bpm_baseline = mean(bpm_baseline),
            mean_bpm_tsst = mean(bpm_tsst),
            mean_bpm_recovery = mean(bpm_recovery))

kable(means_table)

```

